#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TrackMate.Resource", IsApplication=true)]

namespace TrackMate
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::TrackMate.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::TrackMate.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::TrackMate.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::TrackMate.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::TrackMate.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::TrackMate.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::TrackMate.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::TrackMate.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::TrackMate.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::TrackMate.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::TrackMate.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::TrackMate.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::TrackMate.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::TrackMate.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::TrackMate.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::TrackMate.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::TrackMate.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::TrackMate.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::TrackMate.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::TrackMate.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::TrackMate.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::TrackMate.Resource.Layout.test_suite;
			global::Gcm.Client.Resource.String.library_name = global::TrackMate.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo_holder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int progressbar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int track_mate_logo = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int OptionHostName = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int OptionPort = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int OptionRemoteServer = 2131034122;
			
			// aapt resource value: 0x7f05001e
			public const int OptionsButton = 2131034142;
			
			// aapt resource value: 0x7f050019
			public const int ResultFullName = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int ResultMessage = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int ResultResultState = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int ResultRunSingleMethodTest = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int ResultStackTrace = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int ResultsFailed = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int ResultsId = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int ResultsIgnored = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int ResultsInconclusive = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int ResultsMessage = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int ResultsPassed = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int ResultsResult = 2131034130;
			
			// aapt resource value: 0x7f05001d
			public const int RunTestsButton = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int TestSuiteListView = 2131034143;
			
			// aapt resource value: 0x7f050007
			public const int authTokenView = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int email = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int firstName = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int lastName = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int login = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int logout = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int myButton = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int output = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int password = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int progress = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int refreshTokenView = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int register = 2131034117;
			
			// aapt resource value: 0x7f050010
			public const int submit = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int username = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int results = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test_result = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int test_suite = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
